version: '3'

services:
   db:
     image: mysql:latest
     volumes:
       - rhythm_db_data:/var/lib/mysql
       - ./db_data/rhythm_production.sql:/docker-entrypoint-initdb.d/rhythm_production.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./custom-bulk-actions:/var/www/html/wp-content/plugins/custom-bulk-actions/
       - ./prosody_plugin:/var/www/html/wp-content/plugins/prosody_plugin/
       - ./prosody_theme:/var/www/html/wp-content/themes/prosody/
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_TABLE_PREFIX: wp_
volumes:
    rhythm_db_data:
    custom-bulk-actions:
    prosody_plugin:
    prosody_theme:
