version: '2'

services:
   db:
     image: mysql:5.7
     container_name: rhythm_mysql
     volumes:
       - ./rhythm_db_data:/var/lib/mysql

       # Only use this line for the initial start up (the very first time docker-compose is run
       # With this line uncommented, the database will be overwritten using the .sql file
       #- ./initial_sql/rhythm.sql:/docker-entrypoint-initdb.d/rhythm.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     build:
       context: .
     depends_on:
       - db
     image: rhythm_wp:0.2
     container_name: rhythm_wordpress
     volumes:
       - ./wp-custom-bulk-actions:/var/www/html/wp-content/plugins/custom-bulk-actions/
       - ./prosody_plugin:/var/www/html/wp-content/plugins/prosody_plugin/
       - ./prosody_theme:/var/www/html/wp-content/themes/rhythm/
       - ./uploads:/var/www/html/wp-content/uploads/
     ports:
       - ${PORTS}
     restart: always
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
