version: '2'

services:
   rhythm_mysql:
     image: mysql:5.7
     container_name: rhythm_mysql
     volumes:
       - ./rhythm_db_data:/var/lib/mysql

       # Only use this line for the initial start up (the very first time docker-compose is run
       # With this line uncommented, the database will be overwritten using the .sql file
       #- ./initial_sql/rhythm.sql:/docker-entrypoint-initdb.d/rhythm.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     labels:
       - "traefik.enable=false"

   rhythm_wordpress:
     build:
       context: .
     depends_on:
       - rhythm_mysql
     image: rhythm_wp:0.2
     container_name: rhythm_wordpress
     volumes:
       - ./wp-custom-bulk-actions:/var/www/html/wp-content/plugins/custom-bulk-actions/
       - ./prosody_plugin:/var/www/html/wp-content/plugins/prosody_plugin/
       - ./prosody_theme:/var/www/html/wp-content/themes/rhythm/
       - ./uploads:/var/www/html/wp-content/uploads/
     restart: always
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
     labels:
       - "traefik.enable=true"
       - "traefik.docker.network=thenetwork"
       - "traefik.port=80"
       - "traefik.backend=rhythm_wordpress"
       - "traefik.frontend.rule=Host:rhythmofrussian.lib.virginia.edu"

networks:
  default:
    external:
      name: thenetwork
